function synthConfig = gatherSynthConfigFromUI(app)
    % Initialize noise as cell array
    synthConfig = struct(...
        'sampleRate',     app.SampleRateEditField.Value, ...
        'scanPeriod',     app.ScanTimeEditField.Value, ...
        'gain',           app.ResponseGainEditField.Value, ...
        'delay',          app.TimeDelayEditField.Value, ...
        'tau',            app.TimeConstantEditField.Value, ...
        'noise',          {}, ...   % ← MUST BE CELL ARRAY
        'savedOn',        datestr(now) ...
    );

    % Now safely append
    for i = 1:4
        enableBox = app.(['EnableNoise', num2str(i), 'CheckBox']);
        typeDrop = app.(['Noise', num2str(i), 'DropDown']);
        levelField = app.(['Level', num2str(i), 'EditField']);

        if enableBox.Value
            synthConfig.noise{end+1} = struct(...
                'type',  typeDrop.Value, ...
                'level', levelField.Value ...
            );
        end
    end
end