function siteconfig = gatherConfigFromUI(app)
    % Read current display values
    factor = ifelse(app.UnitsToggleButton.Value, 1, 25.4);
    
    siteconfig = struct(...
        'siteName',           app.SiteNameEditField.Value, ...
        'cdControl',          app.CDControlDropDown.Value, ...
        'scannerID',          app.ScannerIDEditField.Value, ...
        'qcsBinWidth_mm',     app.QCSBinWidthEditField.Value * factor, ...
        'qcsBin_numOf',       app.NumOfQCSbinsEditField.Value, ...
        'cdBinWidth_mm',      app.CDBinWidthEditField.Value * factor, ...
        'cdBin_numOf',        app.NumOfCDbinsEditField.Value, ...
        'NumOfAct',           app.NumOfActuatorsEditField.Value, ...
        'actuatorWidth_mm',   app.ActuatorWidthEditField.Value * factor, ...
        'actuatorLoOffset',   app.LoActuatorOffsetEditField.Value, ...
        'actuatorHiOffset',   app.HiActuatorOffsetEditField.Value, ...
        'scannerLoEdge_cdbin',app.LoScannerEdge_cdbinEditField.Value, ...
        'scannerHiEdge_cdbin',app.HiScannerEdge_cdbinEditField.Value, ...
        'savedOn',            datetime("now") ...
    );

    % Update internal storage
    app.InternalQCSBinWidth     = siteconfig.qcsBinWidth_mm;
    app.InternalCDBinWidth      = siteconfig.cdBinWidth_mm;
    app.InternalActuatorWidth   = siteconfig.actuatorWidth_mm;
end